### ISSUE TITLE
cwltool.expression module is missing on cwltool==3.1.20221008225030

### ISSUE THREAD

**Issue by panda1100** [alpha-unito/streamflow#15]
Hi All,

requirements.txt on master branch didn't work for me.

I installed streamflow on Rocky Linux 8 by following procedures.

```
dnf install -y python38 python38-pip
pip3 install -r streamflow/requirements.txt
pip3 install streamflow
```

and 

```
streamflow run --help
```

gives me following error.

```
Traceback (most recent call last):
  File "/usr/local/bin/streamflow", line 5, in <module>
    from streamflow.main import run
  File "/usr/local/lib/python3.8/site-packages/streamflow/main.py", line 15, in <module>
    from streamflow.cwl.main import main as cwl_main
  File "/usr/local/lib/python3.8/site-packages/streamflow/cwl/main.py", line 13, in <module>
    from streamflow.cwl.translator import CWLTranslator
  File "/usr/local/lib/python3.8/site-packages/streamflow/cwl/translator.py", line 30, in <module>
    from streamflow.cwl.command import CWLCommand, CWLExpressionCommand, CWLMapCommandToken, \
  File "/usr/local/lib/python3.8/site-packages/streamflow/cwl/command.py", line 20, in <module>
    from streamflow.cwl import utils
  File "/usr/local/lib/python3.8/site-packages/streamflow/cwl/utils.py", line 5, in <module>
    import cwltool.expression
ModuleNotFoundError: No module named 'cwltool.expression'
```

I checked cwltool repo and found newer than `cwltool==3.1.20220802125926` is missing expression.py. `cwltool==3.1.20220802125926` works fine.

**Comment by GlassOfWhiskey** [comment]
Please feel free to re-open the PR targeting the the `0.1.x` branch.
